### ISSUE TITLE
Hexagon - Broken Module

### ISSUE THREAD

**Issue by migi0027-cdk** [LunarG/LunarGLASS#32]
During the optimization phase (TopToBottom.cpp : runLLVMOptimizations1) some Hexagon intrinsics are generated, which result in an assert:

`Incorrect number of arguments passed to called function!
%1 = call i32 @llvm.hexagon.A2.tfrih.v4f32.v4f32.v3f32.v3f32.v3f32.f32(<4 x float> undef, i32 15, <3 x float> %0, i32
0, <3 x float> %0, i32 1, <3 x float> %0, i32 2, float 1.000000e+00, i32 0)
Stored value type does not match pointer operand type!
store i32 %1, <4 x float>* @_inreturn0, align 16
<4 x float>Broken module found, compilation aborted!`

The `store i32 %1, <4 x float>* @_inreturn0, align 16` section is not my doing, I assume it's something the optimizer changed from this line in the dumped IR:
`store <4 x float> %14, <4 x float>* @_inreturn0`

The error is triggered from this section (dumped ir):
`%7 = load <3 x float>* %geptr`
`%ptr = extractelement <3 x float> %7, i32 0`
`%8 = insertelement <4 x float> undef, float %ptr, i32 0 `
`%ptr4 = extractelement <3 x float> %7, i32 1`
`%9 = insertelement <4 x float> %8, float %ptr4, i32 1`
`%ptr5 = extractelement <3 x float> %7, i32 2`
`%10 = insertelement <4 x float> %9, float %ptr5, i32 2`
`%11 = insertelement <4 x float> %10, float 1.000000e+00, i32 3`
`store <4 x float> %11, <4 x float>* %geptr2`

However I see nothing directly illegal by doing the above, then again I'm new to the LLVM scene.

**Comment by migi0027-cdk** [comment]
The issue occurs when this line in the dumped ir is present:
`%13 = insertelement <4 x float> %12, float 1.000000e+00, i32 3`

When I loaded a float from a temporarily stored alloca instance as such no error occured:
`%17 = load float* %b`
`%18 = insertelement <4 x float> %16, float %17, i32 3`

For me it looks as if insertelement or any pass transforming it has an issue with a value as the scalar operand.

**Comment by greg-lunarg** [comment]
Agreed. Both of these code sequences are legal by my reading of LLVM.

**Comment by migi0027-cdk** [comment]
It appears I was wrong, I misunderstood the situation. The error is induced when I read / load an uniform input and use it later as such:

Declaration:
 `@_inIn0 = global <3 x float> zeroinitializer`

Stored in a wrapper structure:
`%In = alloca %VSIn`
`%0 = getelementptr inbounds %VSIn* %In, i32 0, i32 0`
`%1 = load <3 x float>* @_inIn0`
`store <3 x float> %1, <3 x float>* %0`

The "wrapped" _inIn0 is then accessed by loading:
`%geptr = getelementptr inbounds %VSIn* %In, i32 0, i32 0`

And then the individual elements are extracted and inserted into another vector (With the extra scalar value at the last index).

The respective meta data: (Ignore the _inreturn0-1)
`!gla.inputs = !{!1, !3, !4, !5}`
`!1 = metadata !{metadata !"_inIn0", i32 1, <3 x float>* @_inIn0_typeProxy, metadata !2}`
`!2 = metadata !{i32 7, i32 3, i32 0, null, i32 0, i32 0, i32 -1, i32 0, i32 -1}`
`!3 = metadata !{metadata !"_inIn1", i32 1, <3 x float>* @_inIn1_typeProxy, metadata !2}`
`!4 = metadata !{metadata !"_inreturn0", i32 1, <4 x float>* @_inreturn0_typeProxy, metadata !2}`
`!5 = metadata !{metadata !"_inreturn1", i32 1, <3 x float>* @_inreturn1_typeProxy, metadata !2}`

The metadata & uniform input variable is generated using a function from this rep:
`std::string InName = "_in" + std::string( Name );
        llvm::Value* Inst = State->GLABuilder->createVariable(
                gla::Builder::EStorageQualifier::ESQInput, 0,
                Type, 0, 0, InName
        );

        // Create meta
        State->Meta->makeMdInputOutput(
                InName, gla::InputListMdName,
                Type->isStructTy( ) ? gla::EMdInputOutput::EMioPipeInBlock
                                    : gla::EMdInputOutput::EMioPipeIn,
                GetProxy( State, Type, InName ), Layout, gla::EMdPrecision::EMpHigh,
                0, 0, 0, gla::EInterpolationMethod::EIMNone, gla::EMdBuiltIn::EmbNone
        );`

Again, my LLVM knowledge is not optimal, so I'm sorry if I'm doing anything naive.

**Comment by migi0027-cdk** [comment]
I just noticed the helper function from the "extra" ir builder: createConstructor. I attempted to use this instead of my own "vector constructor", but no luck (Same error, and the IR is identical). This is still sounds like I'm doing something illegal, so in hopes of someone spots it before I do, this is the current program. 

Please note that there are many redundancies, this is currently due to how I translate from a node based compiler and will change (I hope!), currently the translation is quite poor:

http://pastebin.com/i6HTcXra

And for reference, the error is the same:
Incorrect number of arguments passed to called function!
`%1 = call i32 @llvm.hexagon.A2.tfrih.v4f32.v4f32.v3f32.v3f32.v3f32.f32(<4 x float> undef, i32 15, <3 x float> %0, i32 0, <3 x float> %0, i32 1, <3 x float> %0, i32 2, float 1.000000e+00, i32 0)`
`Stored value type does not match pointer operand type!`
`store i32 %1, <4 x float>* @_outreturn0, align 16 <4 x float>Broken module found, compilation aborted!`

**Comment by migi0027-cdk** [comment]
Interestingly enough this is the "broken" but optimized output:

`; ModuleID = 'Top'`
`@_inIn0 = global <3 x float> zeroinitializer`
`@_inIn1 = global <3 x float> zeroinitializer`
`@_outreturn0 = global <4 x float> zeroinitializer`
`@_outreturn1 = global <3 x float> zeroinitializer`
`define fastcc void @main() {`
`entry:`
`  %0 = load <3 x float>* @_inIn0, align 16`
`  %1 = call i32 @llvm.hexagon.A2.tfrih.v4f32.v4f32.v3f32.v3f32.v3f32.f32(<4 x float> undef, i32 15, <3 x float> %0, i32`
`0, <3 x float> %0, i32 1, <3 x float> %0, i32 2, float 1.000000e+00, i32 0)`
`  store i32 %1, <4 x float>* @_outreturn0, align 16`
`  ret void`
`}`
`declare i32 @llvm.hexagon.A2.tfrih.v4f32.v4f32.v3f32.v3f32.v3f32.f32(i32, i32)`
`!gla.entrypoint = !{!0}`
`!gla.inputs = !{!1, !3}`
`!gla.outputs = !{!4, !5}`
`!0 = metadata !{metadata !"main", i32 17}`
`!1 = metadata !{metadata !"_inIn0", i32 1, <3 x float>* @_inIn0_typeProxy, metadata !2}`
`!2 = metadata !{i32 7, i32 3, i32 0, null, i32 0, i32 0, i32 -1, i32 0, i32 -1}`
`!3 = metadata !{metadata !"_inIn1", i32 1, <3 x float>* @_inIn1_typeProxy, metadata !2}`
`!4 = metadata !{metadata !"_outreturn0", i32 9, <4 x float>* @_outreturn0_typeProxy, metadata !2}`
`!5 = metadata !{metadata !"_outreturn1", i32 9, <3 x float>* @_outreturn1_typeProxy, metadata !2}`

**Comment by migi0027-cdk** [comment]
Fixed.

It apperas that I somehow managed to mess up my build of LunarGLASS, resulting in this behaviour (Although to as why I'm not completely sure). I will try to figure out what I did wrong later.

Thank you to anyone who tried to understand my issue, I'm sorry about any time I took since this was on my side.

Regards

**Comment by migi0027-cdk** [comment]
Sorry about the reopen, was an accident.
