### ISSUE TITLE
Specifying descriptor set index

### ISSUE THREAD

**Issue by migi0027-cdk** [LunarG/LunarGLASS#37]
Is there a way to specify which descriptor set a uniform block should be bound to?

**Comment by johnkslang** [comment]
The front-end is set up to pack the descriptor set along with the binding number via `(set << 16) | binding` and save it in the LLVM metadata where the binding is saved.

**Comment by migi0027-cdk** [comment]
Thank you for your quick reply, got it working, really appreciate it.
