### ISSUE TITLE
Push Constants

### ISSUE THREAD

**Issue by migi0027-cdk** [LunarG/LunarGLASS#39]
How are uniform blocks marked as push constants?

**Comment by johnkslang** [comment]
I don't think this has been implemented yet in LunarGLASS.  It is is the glslang AST in the type qualifier's `layoutPushConstant` member.

**Comment by migi0027-cdk** [comment]
Ah I see, I made a small modification for now that should suffice.

BottomToGLSL.cpp, Line: 4318:
`| out << "layout(";`
`| if (layoutStr) {`
`|         out << layoutStr;`
`|         comma = true;`
`| }`
\/\/\/\/\/\/\/\/
`+if (location == gla::MaxUserLayoutLocation + 1) {`
`+if (comma)`
`+out << ", ";`
`+out << "push_constant";`
`+comma = true;`
`+}`

I'm sure this will be invalid glsl for certain conditions, but it should do for now. Thank you for your time!
