### ISSUE TITLE
Add ENABLE_NV_EXTENSIONS and ENABLE_HLSL to CMakeLists.txt

### ISSUE THREAD

**Issue by danginsburg** [LunarG/LunarGLASS#48]
LunarGLASS has gotten out of sync with latest glslang master.  This causes crashes in LunarGOO due to mismatched #define's compiling the two.  The fix is to add the following to CMakeLists.txt in LunarGLASS:

option(ENABLE_NV_EXTENSIONS "Enables support of NV-specific extensions" ON)
option(ENABLE_HLSL "Enables HLSL input support" ON)
if(ENABLE_NV_EXTENSIONS)
    add_definitions(-DNV_EXTENSIONS)
endif(ENABLE_NV_EXTENSIONS)

if(ENABLE_HLSL)
    add_definitions(-DENABLE_HLSL)
endif(ENABLE_HLSL)

**Comment by danginsburg** [comment]
Fix for this issue in PR #50.

**Comment by svenstaro** [comment]
Can't this be closed then?
