### ISSUE TITLE
LunarGLASS does not compile with latest glslang master

### ISSUE THREAD

**Issue by danginsburg** [LunarG/LunarGLASS#49]
The following commit in glslang master removed functions that LunarGOO is using:

https://github.com/KhronosGroup/glslang/commit/a558b26537e47068f027856ab60a9c3ba45ffdbe#diff-9f27b0011955ee30340cd6e37aa3b7b4

**Comment by svenstaro** [comment]
I created a pull request to document this change until more sophisticated solutions come up.
