### ISSUE TITLE
glslang master ENABLE_OPT CMakeLists.txt option needed

### ISSUE THREAD

**Issue by danginsburg** [LunarG/LunarGLASS#60]
The newest version of glslang master adds ENABLE_OPT which defaults to ON.  LunarGLASS CMakeLists.txt needs to be updated with this option and include SPIV-Tools, SPIRV-Tools-opt, and SPVRemapper when it's enabled.  Right now it gets a link error.

**Comment by greg-lunarg** [comment]
Thanks Dan. You can submit your patch as a PR or push a branch and I can submit the PR. Whatever you would prefer.

**Comment by danginsburg** [comment]
Should be fixed by the PR.

**Comment by danginsburg** [comment]
Sorry, I discovered my PR had an error.  This:

    append(GLSLANGLIBS SPVRemapper SPIRV-Tools SPIRV-Tools-opt)

should be this:

    list(APPEND GLSLANGLIBS SPVRemapper SPIRV-Tools SPIRV-Tools-opt)

I can file a new PR if needed.  Sorry for the churn.

**Comment by greg-lunarg** [comment]
Since you have the best understanding of this code at the moment and are probably have everything set up to test it, it would probably be most efficient for you to submit the PR. Thanks!
