### ISSUE TITLE
glslang pointed by the documentation is missing some libs needed by LunarGLASS

### ISSUE THREAD

**Issue by tlorach** [LunarG/LunarGLASS#64]
*SPIRV-Tools.lib* you need for LunarGOO project is missing from https://github.com/KhronosGroup/glslang : the one you ask to use in your readme

On the other hand, SPIRV-Tools libs are available from glslang shipped with Vulkan 1.1.97.0...
But if I try to use it instead, I get other errors during the build.

Surprsing that https://github.com/KhronosGroup/glslang doesn't seem to provide the same as the glslang shipped with VulkanSDK 1.1.97.0

**Comment by danginsburg** [comment]
SPIRV-Tools.lib gets built when you use https://github.com/KhronosGroup/glslang/blob/master/update_glslang_sources.py and build with ENABLE_OPT=On.  Is the problem here that glslang wasn't built with SPIRV-Tools support?

**Comment by tlorach** [comment]
It worked ! Thanks!
