### ISSUE TITLE
Why my program always tell me “Segmentation fault” ????

### ISSUE THREAD

**Issue by SakuraXiaMF** [LunarG/LunarGLASS#69]
I am very sorry to bother you again and again.
I used the command in terminal:
~/Downloads/test/LunarGLASS/build/install/bin$ ./LunarGOO  100ops.frag -t
Then the program tell me "Segmentation fault(core dump)"
The file 100ops.frag is in your  LunarGLASS/test/ folder
I don't know if this error is  due to a problem with my file or because of a problem with my operation.

100ops.frag :
**`
#version 100

lowp float foo();

uniform int low, high;

lowp float face1 = 11.0;

void main()
{
    int z = 3;

    if (2 * low + 1 < high)
        ++z;

    gl_FragColor = face1 * vec4(z) + foo();
}

lowp float face2 = -2.0;

lowp float foo()
{
    // testing if face2 initializer insert logic is correct in main
    return face2;
}`**

**Comment by greg-lunarg** [comment]
I think any time a program ends in a segfault, it is a problem with the program. I would suggest running in a debugger to see the cause of the fault.

LunarGlass was fairly robust and could compile thousands of different, sizeable real life shaders without problem. I think it should handle the shader above without problem.

**Comment by SakuraXiaMF** [comment]
> I think any time a program ends in a segfault, it is a problem with the program. I would suggest running in a debugger to see the cause of the fault.
> 
> LunarGlass was fairly robust and could compile thousands of different, sizeable real life shaders without problem. I think it should handle the shader above without problem.

Tnank your veru much! The program is successful
