### ISSUE TITLE
Current effort?

### ISSUE THREAD

**Issue by seanbaxter** [LunarG/LunarGLASS#74]
Is there a current github repo of code that has this capability? I wrote C++->SPIRV and am looking for SPIRV->SPIRV optimization. Hopefully something I can link against LLVM-8 which I'm already including in my binary.

**Comment by danginsburg** [comment]
For SPIRV -> SPIRV optimization the spirv-opt tools in https://github.com/KhronosGroup/SPIRV-Tools is extremely well maintained and in-use within the Vulkan ecosystem.  It doesn't use LLVM but can be built pretty easily.

**Comment by seanbaxter** [comment]
Cool, thanks.
